test

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -8,10 +8,6 @@ on:
       environment:
         type: string
         description: "environment"
-      website:
-        type: string
-      mail:
-        type: string
       
 jobs:
   test:
@@ -22,4 +18,15 @@ jobs:
        run: echo ${{ inputs.project_name}}.${{ inputs.environment }}
      - name: test2
        run: echo "https://${{ inputs.website }}/${{ inputs.mail}}"
+     - name: Failure
+            run: |
+              if [ "${{ inputs.environment }}" = "nonproduction" ]; then
+                URL="https://google.com/${{ inputs.project_name }}"
+              elif [ "${{ inputs.environment }}" = "preproduction" ]; then
+                URL="https://youtube.com"
+              else [ "${{ inputs.environment }}" = "production" ]; then
+                URL="https://google.com"
+              fi
+              echo "Failed deploy see ArgoCD at $URL"
+              exit 1
 
