fixed

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -22,9 +22,24 @@ jobs:
           URL="https://google.com/${{ inputs.project_name }}"
         elif [ "${{ inputs.environment }}" == "preproduction" ]; then
           URL="https://youtube.com"
-        else [ "${{ inputs.environment }}" == "production" ]; then
+        elif [ "${{ inputs.environment }}" == "production" ]; then
           URL="https://google.com"
+        else
+          URL="https://default.com"
         fi
         echo "Failed deploy see ArgoCD at $URL"
         exit 1
+
+
+    #  - name: Failure
+    #    run: |
+    #     if [ "${{ inputs.environment }}" == "nonproduction" ]; then
+    #       URL="https://google.com/${{ inputs.project_name }}"
+    #     elif [ "${{ inputs.environment }}" == "preproduction" ]; then
+    #       URL="https://youtube.com"
+    #     else [ "${{ inputs.environment }}" == "production" ]; then
+    #       URL="https://google.com"
+    #     fi
+    #     echo "Failed deploy see ArgoCD at $URL"
+    #     exit 1
 
